# Common Application Properties: https://docs.spring.io/spring-boot/appendix/application-properties/

server.port=8080

spring.application.name=m165-m426

spring.datasource.url=jdbc:postgresql://localhost:5432/m165-m426_db
spring.datasource.username=admin
spring.datasource.password=project@bztf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.jpa.show-sql=true
logging.level.sql=DEBUG

# Logging

# Colored Logs
spring.output.ansi.enabled=always

# Use shorter Logging pattern
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint}%clr(%5p) %clr(${PID:- }){magenta} %clr(-){magenta} %clr(%-15.15t){faint} %clr(%-40.40logger{39}){cyan} %clr(:){cyan} %m%n%wEx

# Extra-short pattern
# %clr(%d{HH:mm:ss.SSS}){faint}%clr(%5p) %clr(-){magenta} %clr(%-15.15t){faint} %clr(%-40.40logger{39}){cyan} %clr(:){cyan} %m%n%wEx

# Extended pattern for debugging
# %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(123){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-150.150logger{149}){cyan} %clr(:){faint} %m%n%wEx

# Default built-in pattern for reference
# %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx


# Logging Guide

# Available Log Levels - FATAL, ERROR, WARN, DEBUG, INFO, TRACE
# Global log setting   - logging.level.root=DEBUG
# Logging a class      - logging.level.ch.bztf.m165_m426.HelloWorld=DEBUG
# Wildcards work       - logging.level.org.springframework.data.jpa.*=DEBUG
