spring.application.name=m165-m426

spring.datasource.url=jdbc:postgresql://localhost:5432/m165-m426_db
spring.datasource.username=admin
spring.datasource.password=project@bztf
spring.jpa.hibernate.ddl-auto=update
