# Common Application Properties: https://docs.spring.io/spring-boot/appendix/application-properties/

spring.profiles.active=dev
server.port=8080

spring.application.name=m165-m426

spring.datasource.url=jdbc:postgresql://localhost:5432/m165-m426_db
spring.datasource.username=admin
spring.datasource.password=project@bztf

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true

# Logging

logging.level.sql=DEBUG

# Guide

# Available Log Levels - FATAL, ERROR, WARN, DEBUG, INFO, TRACE
# Global log setting   - logging.level.root=DEBUG
# Logging a class      - logging.level.ch.bztf.m165_m426.HelloWorld=DEBUG
# Wildcards work       - logging.level.org.springframework.data.jpa.*=DEBUG

# Colored Logs
spring.output.ansi.enabled=always

# Logging Patterns

# Shortened pattern
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint}%clr(%6p) %clr([%t]){magenta} %clr(%-40.40logger{39}){cyan} %clr(:){cyan} %m%n%wEx

# Extra-long pattern for debugging
# logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n%wEx

# Default built-in pattern for reference
# %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
